-- Licensing System Tables

-- 1. Table for available Serial Numbers
CREATE TABLE IF NOT EXISTS public.licenses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    serial_number TEXT UNIQUE NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table for Device Activations
CREATE TABLE IF NOT EXISTS public.device_activations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    device_id TEXT UNIQUE NOT NULL, -- Hardware ID / UUID generated by app
    license_id UUID REFERENCES public.licenses(id) ON DELETE SET NULL,
    activated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    trial_started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_trial_active BOOLEAN DEFAULT TRUE
);

-- RLS Policies
ALTER TABLE public.licenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_activations ENABLE ROW LEVEL SECURITY;

-- Anonymous users (app) can check their activation and validate licenses
CREATE POLICY "Apps can check activations" ON public.device_activations
    FOR SELECT USING (true);

CREATE POLICY "Apps can insert activations" ON public.device_activations
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Apps can update own trial" ON public.device_activations
    FOR UPDATE USING (true); -- Better limited by device_id in logic

CREATE POLICY "Public can check license existence" ON public.licenses
    FOR SELECT USING (true);

-- Notify PostgREST
NOTIFY pgrst, 'reload schema';
